<a href="https://colab.research.google.com/github/mlfigueiredo/CienciaDosDados/blob/main/Tuning_Par%C3%A2metros.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Template do Pipeline da Ciência de Dados

# 1. Análise  do problema
# a) Carregar bibliotecas
# b) Carregar conjunto de dados

# 2. Análise Exploratória dos dados - Resumir dados
# a) Estatísticas descritivas
# b) Visualizações de dados

# 3. Pré-Processamento de Dados - Preparar Dados
# a) Limpeza de dados
# b) Seleção de recursos
# c) Transformações de dados (variáveis)

# 4. Construção de Máquinas Preditivas - Avalie Algoritmos
# a) Conjunto de dados de validação dividido
# b) Opções de teste e métrica de avaliação
# c) Algoritmos de verificação pontual
# d) Comparar Algoritmos

# 5. Melhore a precisão
# a) Ajuste de algoritmo
# b) Usar Ensembles

# 6. Finalize o modelo
# a) Previsões no conjunto de dados de validação
# b) Crie um modelo autônomo em todo o conjunto de dados de treinamento
# c) Salve o modelo para uso posterior
# d) Deploy WEB

### Ex: Cálculo do Valor que o BB precisa guardar para possíveis calotes.

Operação 2022

Cliente Marcos Leandro

Ag 8428

Valor de Provisão (calote) = 2.000   (reservas do BB)

In [1]:
!pip install xgboost

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
# Tune learning_rate
from numpy import loadtxt
from xgboost import XGBClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold

In [5]:
# load data
# Posso importar sem o pandas
dataset = loadtxt('pima-data.csv', delimiter=",")
dataset

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [6]:
# split data into X and y
X = dataset[:,0:8]
Y = dataset[:,8]

In [7]:
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [8]:
Y

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 0., 0., 0.

In [16]:
# grid search
model = XGBClassifier()


In [17]:
learning_rate = [0.0001, 0.001, 0.01, 0.1, 0.2, 0.3] 
max_depth= [1, 2, 3, 4, 5]

#Criei um dicionário de dados
param_grid = dict(learning_rate=learning_rate, max_depth= max_depth)

In [18]:
param_grid

{'learning_rate': [0.0001, 0.001, 0.01, 0.1, 0.2, 0.3],
 'max_depth': [1, 2, 3, 4, 5]}

In [19]:
kfold = StratifiedKFold(n_splits=10, shuffle=True, random_state=7)
kfold

StratifiedKFold(n_splits=10, random_state=7, shuffle=True)

In [21]:
grid_search = GridSearchCV(model, param_grid, scoring="neg_log_loss", n_jobs=-1, cv=kfold)
grid_search

GridSearchCV(cv=StratifiedKFold(n_splits=10, random_state=7, shuffle=True),
             estimator=XGBClassifier(), n_jobs=-1,
             param_grid={'learning_rate': [0.0001, 0.001, 0.01, 0.1, 0.2, 0.3],
                         'max_depth': [1, 2, 3, 4, 5]},
             scoring='neg_log_loss')

In [22]:
grid_result = grid_search.fit(X, Y)

In [23]:
grid_result

GridSearchCV(cv=StratifiedKFold(n_splits=10, random_state=7, shuffle=True),
             estimator=XGBClassifier(), n_jobs=-1,
             param_grid={'learning_rate': [0.0001, 0.001, 0.01, 0.1, 0.2, 0.3],
                         'max_depth': [1, 2, 3, 4, 5]},
             scoring='neg_log_loss')

In [24]:
# summarize results
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))

means = grid_result.cv_results_['mean_test_score']

stds = grid_result.cv_results_['std_test_score']

params = grid_result.cv_results_['params']

for mean, stdev, param in zip(means, stds, params):
 print("%f (%f) with: %r" % (mean, stdev, param))

Best: -0.472060 using {'learning_rate': 0.1, 'max_depth': 2}
-0.690795 (0.000241) with: {'learning_rate': 0.0001, 'max_depth': 1}
-0.690138 (0.000410) with: {'learning_rate': 0.0001, 'max_depth': 2}
-0.689712 (0.000402) with: {'learning_rate': 0.0001, 'max_depth': 3}
-0.689592 (0.000450) with: {'learning_rate': 0.0001, 'max_depth': 4}
-0.689468 (0.000657) with: {'learning_rate': 0.0001, 'max_depth': 5}
-0.671640 (0.002664) with: {'learning_rate': 0.001, 'max_depth': 1}
-0.665613 (0.003697) with: {'learning_rate': 0.001, 'max_depth': 2}
-0.661729 (0.003931) with: {'learning_rate': 0.001, 'max_depth': 3}
-0.660956 (0.004246) with: {'learning_rate': 0.001, 'max_depth': 4}
-0.659774 (0.005536) with: {'learning_rate': 0.001, 'max_depth': 5}
-0.575185 (0.016718) with: {'learning_rate': 0.01, 'max_depth': 1}
-0.545870 (0.024282) with: {'learning_rate': 0.01, 'max_depth': 2}
-0.531596 (0.026192) with: {'learning_rate': 0.01, 'max_depth': 3}
-0.527023 (0.029310) with: {'learning_rate': 0.01, 'm

In [25]:
# save the model to disk
from pickle import dump
from pickle import load
filename = 'finalized_model.sav'
dump(grid_search, open(filename, 'wb'))

In [26]:
# some time later...
# load the model from disk
loaded_model = load(open(filename, 'rb'))

In [27]:
loaded_model

GridSearchCV(cv=StratifiedKFold(n_splits=10, random_state=7, shuffle=True),
             estimator=XGBClassifier(missing=nan), n_jobs=-1,
             param_grid={'learning_rate': [0.0001, 0.001, 0.01, 0.1, 0.2, 0.3],
                         'max_depth': [1, 2, 3, 4, 5]},
             scoring='neg_log_loss')